### ISSUE TITLE
ptoblem RAM 

### ISSUE THREAD

**Issue by foxalex2023** [JakeWnuk/ptt#34]
Hi. I generated a dictionary from leaks using a rule of 14 terabytes in size. I cleared it of duplicates and got 6 terabytes. Now I want to apply the top 1000 masks for filtering. I have 500GB of RAM and at one time I can only process a 20GB file.  Is it possible to fix the program so that it consumes less RAM or immediately outputs it to another file?

**Comment by foxalex2023** [comment]
I use                    cat pptf1.txt | ./ptt   -t mask-match -tf topmask1065.txt > pptd2.txt

**Comment by JakeWnuk** [comment]
Hey, thank you for opening an issue.

The command looks good, but the option you are looking for should be implemented already as `-b`:
```
  -b    Bypass map creation and use stdout as primary output.
```

This flag will ignore placing data into a `map` data object and instead print results to `stdout` alleviating memory requirements. To use it, you can include `-b` into ideally any command:
```
$ ptt -b
[*] Bypassing map creation and using stdout as primary output. Options are disabled.
```

This will disable some filtering options, however, as items like deduplication and some filtering are done when all the data is loaded into a map.

For your use case, however, this may take some time regardless. Please let me know if you experience any bugs or issues and I would be happy to help.

I can close this issue in a few days if there are no additional updates!

**Comment by JakeWnuk** [comment]
Hello.

I have pushed `v0.3.2` which contains a fix for the issue with `match` and `-b`. This should resolve your issue as well.

```
$ echo '12345678' | ptt -t mask-match -tf match.lst
12345678

$ echo '12345678' | ptt -t mask-match -tf match.lst -b
[*] Bypassing map creation and using stdout as primary output. Options are disabled.
12345678
```

I cannot say if your job will be successful now, but please let me know if there are any issues and if not, I will close the issue in a day or so.

**Comment by foxalex2023** [comment]
![x](https://github.com/user-attachments/assets/4d92099e-f789-4585-9d7d-5c5bd03e45c6)
With the new version of ptt, the problem persists with a large file. Well, I am very pleased with your program. This is what I was looking for for 2 years and finally found. Filtering the dictionary by masks is the best solution when searching for 1000 slow hashes. This allows you to save 75% on renting a GPU without losing performance. Thank you for your work. For my filter equipment for the top 1000 masks, a dictionary of 15 GB in size works well. The output is usually 5-8 GB of selected passwords

**Comment by JakeWnuk** [comment]
Thank you for the kind words and sorry to hear the issue is persisting.

My test machine has ~128 GB of RAM, and I am having issues replicating the command with ~23 GB of test data as well. Using `-f` instead of accepting input from `stdin` may improve performance, but at this time, I need to do some research and investigation into the issue to see if any additional performance can be squeezed out.

The use case may not be common, but I have had tools in the past handle this better. So stay tuned! If improvements are made, they will be in `v0.3.3` which currently has a development branch.

**Comment by JakeWnuk** [comment]
Hello. I have made a few changes in `v0.3.3` related to this issue.

A file read buffer has been added to `-f` which will allocated a 4 GB buffer for file reads. The previous version allocated ~4 KB. This is a bit overkill, but allows larger files to be loaded and processed faster than the prior implementation. The code for this lives at `/pkg/utils/utils.go:44`.

I was, however, not able to optimize the amount of memory taken by the in-memory map that objects are loaded into. This was an early design choice to be more "context" aware of the data being loaded into transformations and optimize unique transformations. This led to some hard restrictions on the number of items that can be loaded at once. If a file has many unique lines, the amount of memory usage will be higher than a file with duplicates. 

While this does not "fix" the described issue, I hope this change might provide additional flexibility for those working with large amounts of data. I will leave the issue open for a day or so for any discussions and then likely close this issue.

For any future readers, the PR is: 02c0eba0a7545705ab5c7e02f9a4e92a4e509c02
